---
# tasks file for httpdserver
- name: install httpd
  package:
        name: httpd
        state: present

- name: copy webpage to root
  copy:
    src: /home/ebobant/index.html
    dest: /var/www/html/index.html
    mode: 0666

- name: start httpd
  service:
          name: httpd
          state: started

